name: Deploy website on push
description: Deploy website on push
runs:
  using: composite
  steps:
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ inputs.ftp-server }}
        username: ${{ inputs.ftp-username }}
        password: ${{ inputs.ftp-password }}
        local-dir: ./www/dist/
