name: Build and test
description: Docs build and testing
runs:
  using: composite
  steps:
    - name: Install dependencies and build
      run: pnpm install && pnpm build
      shell: bash
      working-directory: ./www
    - name: Tests
      run: pnpm test
      shell: bash
      working-directory: ./www
