name: Docs www pipeline
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
    paths:
      - www/**
  push:
    branches:
      - master
    paths:
      - www/**
defaults:
  run:
    working-directory: www
jobs:
  www-workflow:
    runs-on: ubuntu-latest
    name: WWW workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: ./.github/workflows/actions/setup-node
      - name: Setup pnpm
        uses: ./.github/workflows/actions/setup-pnpm
      - name: Build and test
        uses: ./.github/workflows/actions/www-build-and-test
