name: Docs www pipeline
on:
  pull_request:
    branches:
      - '*'
    paths:
      - www/**
  push:
    branches:
      - master
    paths:
      - www/**
  release:
    types: [published]
    branches:
      - master
defaults:
  run:
    working-directory: www
jobs:
  www-workflow:
    runs-on: ubuntu-latest
    name: WWW workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: ./.github/workflows/actions/setup-node
      - name: Build and test
        uses: ./.github/workflows/actions/www-build-and-test
      - name: Deploy
        if: github.event_name == 'release'
        uses: ./.github/workflows/actions/www-deploy
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
